name: Printing Linux Commands
on:
  workflow_dispatch:

jobs: 
  testing_linux_in_actions:
    runs-on: ubuntu-latest

    steps:
      - name: Print welcome message
        run: echo "Welcome coder"
      - name: Create a directory, two subdirectories, and files in each
        run: |
          mkdir -p test/{a/b,c/d}
          touch test/a/b/file{1..3}.sh test/c/d/file{1..3}.txt
          echo "Just ran something"