name: New
on: 
    push:
      branches:
        - main 
    pull_request:
      branches:
        - main
jobs:
    test_push:
        runs-on: ubuntu-24.04
        steps:
          - name: testing push
            run: echo "Push Test"
          - name: another test
            run: |
             echo "Trying others"
          - name: third
            run: |
             ls -R
             echo "And that's a wrap, $USER"
             echo "A new line"